{{- if eq .Values.loadBalancer.type "istio" }}
{{- range $service := .Values.instanceConfig}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  labels:
    helm.sh/chart: {{ $.Chart.Name }}_{{ $.Chart.Version }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- if $.Chart.AppVersion }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  name: {{ $service.app }}-rule
  {{- if eq $.Release.Namespace "default" }}
  namespace: {{ $.Values.namespace }}
  {{- else }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
spec:
  host: {{ $service.app }}-service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          {{- if eq $service.app "id-web" }}
          name: bold.k8s.id.web.pod.id
          {{- else if eq $service.app "id-api" }}
          name: bold.k8s.id.api.pod.id
          {{- else if eq $service.app "id-ums" }}
          name: bold.k8s.id.ums.pod.id
          {{- else if eq $service.app "reports-web" }}
          name: bold.k8s.reports.web.pod.id
          {{- else if eq $service.app "reports-api" }}
          name: bold.k8s.reports.api.pod.id
          {{- else if eq $service.app "reports-jobs" }}
          name: bold.k8s.reports.jobs.pod.id
          {{- else if eq $service.app "reports-reportservice" }}
          name: bold.k8s.reports.reportservice.pod.id
          {{- else if eq $service.app "reports-viewer" }}
          name: bold.k8s.reports.viewer.pod.id
          {{- end }}          
          ttl: {{ $.Values.loadBalancer.affinityCookie.affinityCookieExpiration }}s
---
{{- end }}
{{- end }}